### ISSUE TITLE
Install fails on Windows. Is it not supported?

### ISSUE THREAD

**Issue by eugeneniemand** [ChrisRx/quickavro#1]
Complete output from command python setup.py egg_info:

```
cl : Command line error D8021 : invalid numeric argument '/Wfatal-errors'
Compiling vendor static library ...
Traceback (most recent call last):
  File "c:\users\eugene.niemand\appdata\local\programs\python\python35-32\lib\distutils\_msvccompiler.py", line 395, in compile
    self.spawn(args)
  File "c:\users\eugene.niemand\appdata\local\programs\python\python35-32\lib\distutils\_msvccompiler.py", line 514, in spawn
    return super().spawn(cmd)
  File "c:\users\eugene.niemand\appdata\local\programs\python\python35-32\lib\distutils\ccompiler.py", line 909, in spawn
    spawn(cmd, dry_run=self.dry_run)
  File "c:\users\eugene.niemand\appdata\local\programs\python\python35-32\lib\distutils\spawn.py", line 38, in spawn
    _spawn_nt(cmd, search_path, dry_run=dry_run)
  File "c:\users\eugene.niemand\appdata\local\programs\python\python35-32\lib\distutils\spawn.py", line 81, in _spawn_nt
    "command %r failed with exit status %d" % (cmd, rc))
distutils.errors.DistutilsExecError: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\cl.exe' failed with exit status 2
```

**Comment by ChrisRx** [comment]
There are a few small tweaks that has to be made to build on windows, like removing some C99 features that are currently used and not supported by the required versions of MSVC, and handling compiler specific flags for different platforms (like the one it is failing on in your traceback `fatal-errors` which is a gcc flag).

The thought also was taking advantage of the platform specific Wheels builds for Windows so that compilation would not be necessary.  I will be looking into those and commenting back as I move forward with add Windows platform-specific support.

**Comment by eugeneniemand** [comment]
Thanks. Maybe add supported platforms or limitations to the home page.
Would have saved me a few hours.

**Comment by ChrisRx** [comment]
I am truly sorry to hear about your lost time, however, I stated this is alpha quality and I'm still currently in the process of adding some platform independence features (I only added single source Python 2/3 like a week ago).  As support for other platforms is added, implicitly or otherwise, those are going to be added to any documentation.

I'm keeping this issue open to report back the progress on Windows platform builds, and close it upon initial Windows platform support.  Hopefully it won't be any issue to have a Windows binary Wheel be built and upload to PyPi so that this will not be difficult for Windows installation in the future.

**Comment by ChrisRx** [comment]
There are some things I'm trying to do that will make quickavro more cross-platform friendly, but at this time, the Windows compiler just isn't up to the task of compiling these C/C++ dependencies with c-avro.  This will unfortunately mean writing my own avro implementation in C, but at the point that happens, I will hopefully be able to comment back in this issue and indicate that better Windows support can be provided.
