### ISSUE TITLE
Unserialized data format is not consistent with other Python Avro implementation

### ISSUE THREAD

**Issue by gth828r** [ChrisRx/quickavro#2]
Hi there!  First of all, thanks for this great project.  For some context, I have been directly using the Encoder `read` and `write` methods to work with byte buffers containing Avro serialized data.  I am hoping to migrate an existing API over to using quickavro under the hood, since it is well, much quicker.

This could be seen as a bug or a feature depending on your angle, but currently there are some inconsistencies in how quickavro represents records as compared to the other Python Avro implementations:

1. Enum types appear to use a custom quickavro `Enum` class that requires a re-definition of the sybmols in the code to match the schema, while Apache Avro implementation uses Python strings to represent the symbols.
2.  Looking at some of the serialization code, it appears that the Fixed type is calling `_PyUnicode_CheckExact` when for Validation.  That check will check for either a Python3 string or a Python2 unicode object.  The Apache Avro implementation uses bytes type to represent this data.

Are these two deviations intentional?  Would you consider falling in line with what the Apache Avro implementation does in order to potentially increase adoption?  I hacked together something that kind-of works for me with my old data build for the Apache Avro Python implementation, and I can submit a PR for those changes if you'd consider a switch.

**Comment by ChrisRx** [comment]
I'm definitely open to a PR, I actually wrote this really fast even though I didn't really need it for anything, and then just didn't come back to it, so there are definitely a lot of things that can improve it.  With the Enum type (and it has been a while since I have looked at this so I have since forgotten what I had even done, so please forgive me if I misunderstand  something) I thought I set it up so that you could use the custom Python enum type as a way of writing it more naturally and having an easier time doing lookup's (C int's vs char*/strcmp), but that it would be compatible both ways using the custom Enum class and a regular string (or definitely should).  Do you have a good example to share that could help reproduce what you are seeing?

If the Fixed type is suppose to be Bytes by the spec then it is just a mistake that could be fixed.  As I said, I wrote this really fast and took a lot of things like [this](https://avro.apache.org/docs/1.8.1/spec.html#Fixed) at face value where it said it was a "string".  I would defer to your Avro expertise for sure so just include that check in the PR if that is cool with you.

I'm still reading through the other issues you have, but they all seem like correct observations so if you get a PR prepared to fix the bugs I will definitely accept it, everything looks great.  I really appreciate your interest and would certainly do a better job supporting this knowing someone is actually using it for something (I could do a once over again with the code also and make some C improvements to ensure it isn't leaking memory, is optimal, etc).

**Comment by gth828r** [comment]
> Do you have a good example to share that could help reproduce what you are seeing?

I did not actually try the path of using the custom enum type, so for all I know it works OK.  The line that I was seeing problems at with my string-represented enum was https://github.com/ChrisRx/quickavro/blob/master/src/convert.c#L229.  Based on what you are saying and looking at that code, I think I really should not have been hitting that line.  Now that I understand what you were going for, I think the fix is probably different.  I'll need to go back and reproduce the error so I can understand why I was not hitting https://github.com/ChrisRx/quickavro/blob/master/src/convert.c#L225, but my current guess is maybe the issue was happening in Python2, and Python3 did not require my change to work properly.

> If the Fixed type is suppose to be Bytes by the spec then it is just a mistake that could be fixed.

After looking over the spec, I agree with you that it is very vague on the Fixed type.  https://avro.apache.org/docs/1.8.1/spec.html#order hints at Fixed being of the same form as Bytes, but that is about it.  I am mostly working off of experience with the implementations of C, C++, and Py2/Py3 provided by Apache.  I know from playing with those that passing in a collection of raw unsigned 8-bit values is what the APIs they provide expect for Fixed types.  In the case of Python2 that means a str type, and in the case of Python3 that means a bytes type.  I *think* your Bytes encoding is working OK, so we probably just want to mirror what you are doing there for the Fixed type.  I have not looked closely at the output, but at least on serialization nothing is complaining.  I'll try to deserialize some records to be sure that nothing barfs there after using my updated serialization code.

> I really appreciate your interest and would certainly do a better job supporting this knowing someone is actually using it for something

No no, you're the one that did most of the heavy lifting here. :smile: 

We have been using Avro to serialize data to byte buffers for Kafka, and some of our development partners need better performance with Python than what native Apache Avro's Python implementation provides.  I found that your `BinaryEncoder` actually supported "read" out of the box for us, so I wanted to start looking into "write".  We've already switched over to quickavro for our deserialization and saw an order of magnitude improvement in performance.

I'll start working on these things as soon as I can.  I'll submit separate PRs for each issue since they are all pretty independent of each other.

**Comment by gth828r** [comment]
> I'll need to go back and reproduce the error so I can understand why I was not hitting https://github.com/ChrisRx/quickavro/blob/master/src/convert.c#L225, but my current guess is maybe the issue was happening in Python2, and Python3 did not require my change to work properly.

This was indeed a py2/3 compatibility issue.  https://github.com/ChrisRx/quickavro/blob/master/src/convert.c#L224 works just fine for string-formatted enum values under Python3, but not under Python2.  I think this could be addressed by calling your existing `_PyUnicode_CheckExact` compatibility macro, but the "CheckExact" part would also be different from the existing code, which just calls `PyUnicode_Check`.  In testing I didn't notice an issue, but I honestly have no clue what the subtypes of the Unicode type might be, and if you should expect to support them for Enums.  Do you recall if there was a specific reason not to use `PyUnicode_CheckExact` there?

**Comment by gth828r** [comment]
The Enum and Fixed issues I reported originally are somewhat separate.  This is especially true now that I understand your intention with the enums.  I am going to split the changes for the Fixed type into a separate ticket, as it will make applying that change more simple.  The changes for the Enum stuff will require a bit more care to get it right.

Also, somewhat unfortunately, the enum stuff may tie into #6.  I'll continue to think on those, but I'll submit PRs for the other changes.
